apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    labels:
        app: nginx-lab
spec:
    type: NodePort
    selector:
        app: nginx-lab
    ports:
        - name: http
          port: 80
          targetPort: 80
          nodePort: 30080 # NodePort 必須在 30000-32767
